controller_manager:
  ros__parameters:
    update_rate: 50

    auv_wrench_controller:
      type: auv_controllers/BodyWrenchController

    auv_velocity_controller:
      type: auv_controllers/BodyVelocityController
      
    # pid_controller:
    #   type: pid_controller/PidController

auv_wrench_controller:
  ros__parameters:
    num_thrusters: 2

    thruster_joint_names:
     - auv/thruster3_joint
     - auv/thruster4_joint

    thruster_allocation_matrix: 
      [0.707107, 0.707107,      # X
       0.707107, -0.707107,     # Y
       0.0, 0.0,                # Z
       0.0, 0.0,                # roll
       0.0, 0.0,                # pitch
       -0.495, 0.495]           # yaw

# DEFINE THE EXPOSED INTERFACES IN THE WRENCH AND THE REQUIRED IN THE VELOCITY WHEN IS CHAINED
# MAKE THE ODOM TO VELOCITY NODE FOR FEEDBACK
auv_velocity_controller:
  ros__parameters:
    num_thrusters: 2
    body_velocity_state_topic: auv/navigator/velocity
    # chain parameters
    dof_names:
      - auv_wrench_controller/x
      - auv_wrench_controller/yaw
    command_interface: force
    

pid_controller:
  ros__parameters:
    dof_names:
      - auv_wrench_controller/x
      - auv_wrench_controller/yaw
    command_interface: velocity
    reference_and_state_interfaces: ["velocity"]

    gains:
      # control the velocity, no d term
      auv_wrench_controller/x: {"p": 0.5, "i": 2.5, "d": 0.0}