<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="auv_bot" params="parent prefix *origin">

    <!-- Constants for robot dimensions -->
    <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
    <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
    <xacro:property name="height1" value="2" /> <!-- Link 1 -->
    <xacro:property name="height2" value="1" /> <!-- Link 2 -->
    <xacro:property name="height3" value="1" /> <!-- Link 3 -->
    <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

    <!-- Base Link -->
    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.1 0.1 0.1" />
        </geometry>
        <material name="orange" />
      </visual>
    </link>

    <!-- Middle Link -->
    <link name="${prefix}link1">
      <collision>
        <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0" />
        <geometry>
          <box size="${width} ${width} ${height2}" />
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0" />
        <geometry>
          <box size="${width} ${width} ${height2}" />
        </geometry>
        <material name="yellow" />
      </visual>
    </link>

    <!-- Top Link -->
    <link name="${prefix}link2">
      <visual>
        <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0" />
        <geometry>
          <box size="${width} ${width} ${height3}" />
        </geometry>
        <material name="orange" />
      </visual>
    </link>

    <joint name="${prefix}joint1" type="continuous">
      <parent link="${prefix}base_link" />
      <child link="${prefix}link1" />
      <origin xyz="0 ${width} ${height1 - axel_offset}" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <limit effort="100" velocity="1.0" />
    </joint>

    <joint name="${prefix}joint2" type="continuous">
      <parent link="${prefix}link1" />
      <child link="${prefix}link2" />
      <origin xyz="0 ${width} ${height2 - axel_offset*2}" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <limit effort="100" velocity="1.0" />
    </joint>

  </xacro:macro>

</robot>