controller_manager:
  ros__parameters:
    update_rate: 20  # Hz

    robot_hardware:
      type: stonefish_hw_interface/ThrusterGroupHWInterface

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_state_broadcaster:
  ros__parameters:
    use_local_topics: false